"""DIMER inference package for the pinned ``CIDAS/clipseg-rd64-refined`` checkpoint."""

from .pipeline import (
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    LOGIT_SIZE,
    MASK_THRESHOLD,
    MAX_IMAGE_SIDE,
    MAX_PROMPT_CHARS,
    MAX_PROMPTS,
    MAX_TEXT_TOKENS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    ClipSegSegmentationPipeline,
    evaluation_report,
    format_prompts,
    mask_bbox,
    mask_iou,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "LOGIT_SIZE",
    "MASK_THRESHOLD",
    "MAX_IMAGE_SIDE",
    "MAX_PROMPTS",
    "MAX_PROMPT_CHARS",
    "MAX_TEXT_TOKENS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "ClipSegSegmentationPipeline",
    "evaluation_report",
    "format_prompts",
    "mask_bbox",
    "mask_iou",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
]
